name: "Manual Scrape"

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager pymongo
        working-directory: ./backend

      - name: Run scraper
        run: |
          python usf_menu_scrapper.py
        working-directory: ./backend
